In [1]:
import pickle
import time
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

from tdamapper.core import MapperAlgorithm
from tdamapper.cover import CubicalCover
from tdamapper.plot import MapperLayoutInteractive, MapperLayoutStatic
from tdamapper.clustering import FailSafeClustering
from sklearn import metrics

from functions import *
from chi import *
from regressionP import *
from models import *

In [2]:
data1 = pd.read_csv("./Data/NPA_TMA2_1.csv", low_memory=False)[:-2]
data2 = pd.read_csv("./Data/NPA_TMA2_2.csv", low_memory=False)[:-2]
data3 = pd.read_csv("./Data/NPA_TMA2_3.csv", low_memory=False)[:-2]
data4 = pd.read_csv("./Data/NPA_TMA2_4.csv", low_memory=False)[:-2]

dataA2 = pd.concat([data1, data2, data3, data4], ignore_index=True)

# dataA1 = pd.read_csv("./Data/A1_617.csv")[:-2]
dataA1 = pd.read_csv("./Data/NPA_TMA1.csv")[:-2]

In [3]:
def preprocess(input_data, select_lst, sample = 592):
    sample_data = input_data[input_data['當事者順位'] == 1].reset_index(drop=True, inplace=False)#.sample(sample).reset_index(drop=True)
    # sample_data = sample_data[sample_data['發生月份'] < 3]
    dataA = sample_data[select_lst]
    
    death_injury_data = split_death_injury(dataA['死亡受傷人數'])
    dist_df = pd.concat([dataA, death_injury_data], axis=1)
    dist_df.drop(columns=['死亡受傷人數'], inplace=True)
    
    return dist_df, sample_data

# List of columns to select
select_lst = [
    '光線名稱',
    '道路類別-第1當事者-名稱',
    '速限-第1當事者', #'道路障礙-視距品質名稱', # 和速限共線
    '道路型態大類別名稱', '事故位置大類別名稱', 
    '路面狀況-路面鋪裝名稱', '路面狀況-路面缺陷名稱', '道路障礙-障礙物名稱', # 分類幾乎都是無缺陷
    '號誌-號誌種類名稱',
    '車道劃分設施-分向設施大類別名稱', '車道劃分設施-分道設施-快車道或一般車道間名稱',
    '車道劃分設施-分道設施-快慢車道間名稱', '車道劃分設施-分道設施-路面邊線名稱',
    '事故類型及型態大類別名稱',
    '死亡受傷人數',
    '經度', '緯度',
]

dist_dfA1 = preprocess(dataA1, select_lst, sample = 592)
dist_dfA2 = preprocess(dataA2, select_lst, sample = 20000) # 120420

rbind_data = pd.concat([dist_dfA1[0], dist_dfA2[0]], axis=0, ignore_index=True)

rbind_data.loc[rbind_data['受傷'] > 1, '受傷'] = 2
rbind_data['速限-第1當事者'] = rbind_data['速限-第1當事者'].apply(lambda x: 1 if x > 60 else 0)

dist_df = process_data(rbind_data)
scaler = StandardScaler()

full_dist = pd.DataFrame(scaler.fit_transform(dist_df), columns = dist_df.columns)
X1 = full_dist.drop(['受傷', '死亡', '經度', '緯度'], axis=1).to_numpy()

full_dist.head()

光線名稱  道路類別-第1當事者-名稱  速限-第1當事者  道路型態大類別名稱  事故位置大類別名稱  路面狀況-路面鋪裝名稱  \
0  0.146102       2.120706 -0.146069   1.210906   0.485564    -0.045604   
1  1.465217      -0.251720 -0.146069  -0.814068  -0.872635    -0.045604   
2 -1.173013       2.911514 -0.146069   1.210906   1.164664    -0.045604   
3 -1.173013      -0.251720 -0.146069  -0.814068  -0.872635    -0.045604   
4  1.465217       2.120706 -0.146069   1.210906   1.164664    -0.045604   

   路面狀況-路面缺陷名稱  道路障礙-障礙物名稱  號誌-號誌種類名稱  車道劃分設施-分向設施大類別名稱  \
0    -0.029347    0.001515  -0.713755         -1.627801   
1    -0.029347    0.001515   2.771975         -1.627801   
2    -0.029347    0.001515  -0.713755          1.177412   
3    -0.029347    0.001515   2.771975         -0.225194   
4    -0.029347    0.001515  -0.713755          0.476109   

   車道劃分設施-分道設施-快車道或一般車道間名稱  車道劃分設施-分道設施-快慢車道間名稱  車道劃分設施-分道設施-路面邊線名稱  \
0                 1.771301            -1.697696           -0.917071   
1                -0.822895            -1.697696           -0.917071   
2                 1.122752            -1.697696           -0.917071   
3                -0.822895             0.422707            1.090428   
4                -0.822895             0.422707           -0.917071   

   事故類型及型態大類別名稱        經度        緯度         死亡        受傷  
0      1.798967 -0.634220 -1.868211  13.660843 -2.803204  
1     -0.012319  1.111877  0.974928  13.660843 -0.620846  
2      1.798967 -2.459704 -0.633180  13.660843 -2.803204  
3     -0.012319  0.936797  1.016777  13.660843 -0.620846  
4      1.798967  1.832866  0.186897  13.660843 -2.803204

In [7]:
start_time = time.time()

# lens1 = PCA(10).fit_transform(X1)

# mapper_algo1 = MapperAlgorithm(
#     cover = CubicalCover(
#         n_intervals = 4,
#         overlap_frac = 0.5
#     ),
#     clustering = FailSafeClustering(
#         clustering = AgglomerativeClustering(3, linkage='ward'),
#         verbose = False)
# )

mapper_graph1 = mapper_algo1.fit_transform(X1, lens1)

end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

MemoryError: Unable to allocate 18.5 GiB for an array with shape (2476496253,) and data type float64

In [ ]:
# 道路型態大類別名稱
mapper_plot1 = MapperLayoutInteractive(
    mapper_graph1,
    colors = dist_df[['速限-第1當事者']].to_numpy(),
    cmap = 'jet',
    # agg = np.nanmean,
    agg = most_frequent_nonan,
    dim = 3,
    iterations = 30,
    seed = 6,
    width = 800,
    height = 500)

fig_mean1 = mapper_plot1.plot()
fig_mean1.show(config={'scrollZoom': True})

In [116]:
import pickle

with open('CalculatedData/道路V2.pkl', 'wb') as f:
    pickle.dump(mapper_graph1, f)

# 模型比較

In [142]:
def preprocess(input_data, select_lst, sample = 592):
    sample_data = input_data[input_data['當事者順位'] == 1].reset_index(drop=True, inplace=False)#.sample(sample).reset_index(drop=True)
    # sample_data = sample_data[sample_data['發生月份'] < 3]
    dataA = sample_data[select_lst]
    
    death_injury_data = split_death_injury(dataA['死亡受傷人數'])
    dist_df = pd.concat([dataA, death_injury_data], axis=1)
    dist_df.drop(columns=['死亡受傷人數'], inplace=True)
    
    return dist_df, sample_data

# List of columns to select
select_lst = [
    '天候名稱', 
    '路面狀況-路面狀態名稱',
    '肇因研判大類別名稱-主要', '當事者屬-性-別名稱', '當事者事故發生時年齡', 
    '車輛撞擊部位大類別名稱-最初',
    '光線名稱',
    '道路類別-第1當事者-名稱',
    '速限-第1當事者', 
    '道路型態大類別名稱',
    '事故位置大類別名稱', 
    '號誌-號誌種類名稱',
    '車道劃分設施-分向設施大類別名稱', '車道劃分設施-分道設施-快車道或一般車道間名稱',
    '車道劃分設施-分道設施-快慢車道間名稱', '車道劃分設施-分道設施-路面邊線名稱',
    '事故類型及型態大類別名稱',
    '死亡受傷人數',
    '經度', '緯度',
    '道路型態子類別名稱', '事故位置子類別名稱', '車道劃分設施-分向設施子類別名稱', '事故類型及型態子類別名稱', 
    '當事者行動狀態子類別名稱', '車輛撞擊部位子類別名稱-最初', '車輛撞擊部位子類別名稱-其他', '肇因研判子類別名稱-個別',
    
    '當事者區分-類別-大類別名稱-車種', '當事者區分-類別-子類別名稱-車種',
    '保護裝備名稱', '行動電話或電腦或其他相類功能裝置名稱', '當事者行動狀態大類別名稱',
    '車輛撞擊部位大類別名稱-其他', '肇因研判大類別名稱-個別', '肇事逃逸類別名稱-是否肇逃',
    '路面狀況-路面鋪裝名稱', '路面狀況-路面缺陷名稱',
    '道路障礙-障礙物名稱', '道路障礙-視距品質名稱', '道路障礙-視距名稱','號誌-號誌動作名稱',
]

dist_dfA1 = preprocess(dataA1, select_lst, sample = 592)
dist_dfA2 = preprocess(dataA2, select_lst, sample = 11840) # 120420

rbind_data = pd.concat([dist_dfA1[0], dist_dfA2[0]], axis=0, ignore_index=True)

rbind_data.loc[rbind_data['受傷'] > 1, '受傷'] = 2
rbind_data['速限-第1當事者'] = rbind_data['速限-第1當事者'].apply(lambda x: 1 if x > 60 else 0)
rbind_data = process_age(rbind_data)

dist_df = process_data(rbind_data)
scaler = StandardScaler()

full_dist = pd.DataFrame(scaler.fit_transform(dist_df), columns = dist_df.columns)
X1 = full_dist.drop(['受傷', '死亡'], axis=1).to_numpy()

full_dist.head()

天候名稱  路面狀況-路面狀態名稱  肇因研判大類別名稱-主要  當事者屬-性-別名稱  當事者事故發生時年齡  \
0 -0.447747    -0.331183      0.509425    0.739901    -1.09744   
1 -0.447747    -0.331183      0.509425    0.739901     0.67326   
2  1.201000    -0.331183      0.509425    0.739901     0.67326   
3 -0.447747    -0.331183      0.509425    0.739901    -0.21209   
4  1.201000    -0.331183      0.509425    0.739901    -1.09744   

   車輛撞擊部位大類別名稱-最初      光線名稱  道路類別-第1當事者-名稱  速限-第1當事者  道路型態大類別名稱  ...  \
0       -0.372169  0.146102       2.120706 -0.146069   1.210906  ...   
1        1.175119  1.465217      -0.251720 -0.146069  -0.814068  ...   
2       -0.372169 -1.173013       2.911514 -0.146069   1.210906  ...   
3       -0.372169 -1.173013      -0.251720 -0.146069  -0.814068  ...   
4       -0.372169  1.465217       2.120706 -0.146069   1.210906  ...   

   肇因研判大類別名稱-個別  肇事逃逸類別名稱-是否肇逃  路面狀況-路面鋪裝名稱  路面狀況-路面缺陷名稱  道路障礙-障礙物名稱  \
0      0.508523      -0.135001    -0.045604    -0.029347    0.001515   
1      0.508523      -0.135001    -0.045604    -0.029347    0.001515   
2      0.508523      -0.135001    -0.045604    -0.029347    0.001515   
3      0.508523      -0.135001    -0.045604    -0.029347    0.001515   
4      0.508523      -0.135001    -0.045604    -0.029347    0.001515   

   道路障礙-視距品質名稱  道路障礙-視距名稱  號誌-號誌動作名稱         死亡        受傷  
0     0.118545   0.060048   0.837867  13.660843 -2.803204  
1     0.118545   0.060048  -1.192531  13.660843 -0.620846  
2     0.118545   0.060048   0.837867  13.660843 -2.803204  
3     0.118545   0.060048  -1.192531  13.660843 -0.620846  
4     0.118545   0.060048   0.837867  13.660843 -2.803204  

[5 rows x 43 columns]

In [144]:
dist_df

天候名稱  路面狀況-路面狀態名稱  肇因研判大類別名稱-主要  當事者屬-性-別名稱  當事者事故發生時年齡  \
0          0            0             9           3           1   
1          0            0             9           3           3   
2          1            0             9           3           3   
3          0            0             9           3           2   
4          1            0             9           3           1   
...      ...          ...           ...         ...         ...   
121007     1            0             9           3           2   
121008     0            0             9           3           2   
121009     0            0             9           3           2   
121010     0            0             9           3           3   
121011     0            0             9           3          -1   

        車輛撞擊部位大類別名稱-最初  光線名稱  道路類別-第1當事者-名稱  速限-第1當事者  道路型態大類別名稱  ...  \
0                    1     1              6         0          2  ...   
1                    2     2              3         0          0  ...   
2                    1     0              7         0          2  ...   
3                    1     0              3         0          0  ...   
4                    1     2              6         0          2  ...   
...                ...   ...            ...       ...        ...  ...   
121007               2     0              3         0          0  ...   
121008               1     0              3         0          2  ...   
121009               1     0              3         0          2  ...   
121010               2     0              3         0          0  ...   
121011               0     2              5         0          2  ...   

        肇因研判大類別名稱-個別  肇事逃逸類別名稱-是否肇逃  路面狀況-路面鋪裝名稱  路面狀況-路面缺陷名稱  道路障礙-障礙物名稱  \
0                  9              0            1            1           3   
1                  9              0            1            1           3   
2                  9              0            1            1           3   
3                  9              0            1            1           3   
4                  9              0            1            1           3   
...              ...            ...          ...          ...         ...   
121007             9              0            1            1           3   
121008             9              0            1            1           3   
121009             9              0            1            1           3   
121010             9              0            1            1           3   
121011             9              0            1            1           3   

        道路障礙-視距品質名稱  道路障礙-視距名稱  號誌-號誌動作名稱  死亡  受傷  
0                 1          4          3   1   0  
1                 1          4          1   1   1  
2                 1          4          3   1   0  
3                 1          4          1   1   1  
4                 1          4          3   1   0  
...             ...        ...        ...  ..  ..  
121007            1          4          1   0   1  
121008            1          4          1   0   1  
121009            1          4          3   0   1  
121010            0          5          3   0   1  
121011            1          4          3   0   1  

[121012 rows x 43 columns]

In [145]:
with open('CalculatedData/道路V2.pkl', 'rb') as f:
    mapper_graph1 = pickle.load(f)
    
mapper_plot1 = MapperLayoutInteractive(
    mapper_graph1,
    colors = dist_df[['速限-第1當事者']].to_numpy(),
    cmap = 'jet',
    # agg = np.nanmean,
    agg = most_frequent_nonan,
    dim = 3,
    iterations = 30,
    seed = 6,
    width = 800,
    height = 500)

In [146]:
x = vars(mapper_plot1._MapperLayoutInteractive__fig)['_data_objs'][1]['x']
y = vars(mapper_plot1._MapperLayoutInteractive__fig)['_data_objs'][1]['y']
z = vars(mapper_plot1._MapperLayoutInteractive__fig)['_data_objs'][1]['z']

threeDimData = pd.DataFrame({'x': x, 'y': y, 'z': z})

import re
data_tuple = vars(mapper_plot1._MapperLayoutInteractive__fig)['_data_objs'][1]['text']

data = []
for item in data_tuple:
    color = int(re.search(r'color: (-?\d+)', item).group(1))
    node = int(re.search(r'node: (\d+)', item).group(1))
    size = int(re.search(r'size: (\d+)', item).group(1))
    data.append({'color': color, 'node': node, 'size': size})
        
component_info = pd.DataFrame(data)

full_info = pd.concat([component_info, threeDimData], axis=1)

mp_content_origin = vars(mapper_plot1._MapperLayoutInteractive__graph)['_node']

mp_content = pd.DataFrame.from_dict(mp_content_origin, orient='index')
mp_content.reset_index(inplace=True)
mp_content.rename(columns={'index': 'node'}, inplace=True)

full_info = pd.merge(full_info, mp_content, on=['node', 'size'], how='inner')

In [147]:
calinski_data = get_calinski_from_db(full_info, 0.045)
labels = calinski_data[3]
db = calinski_data[2]
n_clusters_ = calinski_data[4]

unique_labels = set(labels)
core_samples_mask = np.zeros_like(labels, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True

def matplotlib_to_plotly(cmap, alpha=1):
    """rgba"""
    return f'rgba({int(cmap[0]*200)}, {int(cmap[1]*200)}, {int(cmap[2]*200)}, {alpha})'

colors = [matplotlib_to_plotly(plt.cm.Spectral(each), alpha=0.8) for each in np.linspace(0, 1, len(unique_labels))]
fig = go.Figure()

for k, col in zip(unique_labels, colors):
    if k == -1:
        col = 'rgba(0,0,0,0)'

    class_member_mask = labels == k

    core_samples = full_info.iloc[:, 3:6][class_member_mask & core_samples_mask]
    fig.add_trace(go.Scatter3d(
        x=core_samples.iloc[:, 0],
        y=core_samples.iloc[:, 1],
        z=core_samples.iloc[:, 2],
        mode='markers',
        marker=dict(
            size=6,
            color=col,
            opacity=0.8
        ),
        name=f'Cluster {k} Core'
    ))

    non_core_samples = full_info.iloc[:, 3:6][class_member_mask & ~core_samples_mask]
    fig.add_trace(go.Scatter3d(
        x=non_core_samples.iloc[:, 0],
        y=non_core_samples.iloc[:, 1],
        z=non_core_samples.iloc[:, 2],
        mode='markers',
        marker=dict(
            size=6,
            color=col,
            opacity=0.5
        ),
        name=f'Cluster {k} Non-Core'
    ))

fig.update_layout(
    title=f"Estimated number of clusters: {n_clusters_}",
    margin=dict(l=0, r=0, b=0, t=0)
)

fig.show()

In [162]:
# 0.045 預測最好
calinski_data = get_calinski_from_db(full_info, 0.045)

label_0 = full_info[full_info['label'] == 0]
label_1 = full_info[full_info['label'] == 1]
label_2 = full_info[full_info['label'] == 2]
label_out = full_info[full_info['label'] == -1]

count_0 = get_count_dict(label_0)
count_1 = get_count_dict(label_1)
count_2 = get_count_dict(label_2)
count_out = get_count_dict(label_out)

print(full_info['label'].unique())

len(count_out)

[ 0  1  2 -1]


113

In [149]:
full_0 = rbind_data.loc[count_0.keys()]
full_1 = rbind_data.loc[count_1.keys()]
full_2 = rbind_data.loc[count_2.keys()]

# 離群值不需要被處理
full_out = rbind_data.loc[count_out.keys()]

lst01 = list(count_0.keys() & count_1.keys())
lst02 = list(count_0.keys() & count_2.keys())
lst12 = list(count_1.keys() & count_2.keys())
lsto0 = list(count_out.keys() & count_0.keys())
lsto1 = list(count_out.keys() & count_1.keys())
lsto2 = list(count_out.keys() & count_2.keys())

# 將重複的key另外拉出進行分析，這裡drop是為了符合卡方的獨立性前提假設
full_01 = full_0.loc[lst01]
full_02 = full_0.loc[lst02]
full_12 = full_1.loc[lst12]

full_combine = pd.concat([full_01, full_02, full_12], axis=0) # full_out
full_combine = full_combine.reset_index()
full_combine = full_combine.drop_duplicates(subset='index', keep='first')
full_combine = full_combine.drop('index', axis=1)
# 去掉連接點，使分析更嚴謹
full_0 = full_0.drop(lst01 + lst02 + lsto0, errors='ignore')
full_1 = full_1.drop(lst01 + lst12 + lsto1, errors='ignore')
full_2 = full_2.drop(lst02 + lst12 + lsto2, errors='ignore')

print('01連接點數量', len(lst01))
print('02連接點數量', len(lst02))
print('12連接點數量', len(lst12))
print('o0連接點數量', len(lsto0))
print('o1連接點數量', len(lsto1))
print('o2連接點數量', len(lsto2))
print('離群值數量', full_out.shape[0])

full_combine.shape[0] + full_0.shape[0] + full_1.shape[0] + full_2.shape[0] == rbind_data.shape[0]

01連接點數量 220
02連接點數量 0
12連接點數量 0
o0連接點數量 12
o1連接點數量 6
o2連接點數量 13
離群值數量 113


False

In [84]:
full_out.to_csv('CalculatedData/離群比較/拓樸V2.csv', index=False)

In [150]:
lst_logit = [
    '路面狀況-路面狀態名稱',
    '當事者屬-性-別名稱', '當事者事故發生時年齡', 
    '車輛撞擊部位大類別名稱-最初',
    '光線名稱',
    '道路類別-第1當事者-名稱',
    '速限-第1當事者',
    '道路型態大類別名稱',
    '事故位置大類別名稱', 
    '號誌-號誌種類名稱',
    '車道劃分設施-分向設施大類別名稱', '車道劃分設施-分道設施-快車道或一般車道間名稱',
    '車道劃分設施-分道設施-快慢車道間名稱', '車道劃分設施-分道設施-路面邊線名稱',
    '事故類型及型態大類別名稱',
    '事故位置子類別名稱', '事故類型及型態子類別名稱', 
    '當事者行動狀態子類別名稱',
    '車輛撞擊部位子類別名稱-最初', '肇因研判子類別名稱-個別',
    '當事者區分-類別-子類別名稱-車種',
    '保護裝備名稱', '行動電話或電腦或其他相類功能裝置名稱', 
    '當事者行動狀態大類別名稱',
    '車輛撞擊部位大類別名稱-其他', 
    '肇因研判大類別名稱-個別', '肇事逃逸類別名稱-是否肇逃',
    '路面狀況-路面鋪裝名稱', 
    '車道劃分設施-分向設施子類別名稱',
    '道路障礙-障礙物名稱', '車輛撞擊部位子類別名稱-其他'
    
    # '號誌-號誌動作名稱', '當事者區分-類別-大類別名稱-車種', '肇因研判大類別名稱-主要' # 降低預測值
    # '道路障礙-視距名稱', '車道劃分設施-分道設施-快慢車道間名稱', '車輛撞擊部位大類別名稱-其他' # 降低預測值
    # '道路型態子類別名稱', '路面狀況-路面缺陷名稱', '天候名稱' # 降低
]

def get_clusterN_logit(cluster_data, lst):
    scaler = StandardScaler()
    
    c0_for_lm = process_data(cluster_data)
    c0_for_lm_X = pd.DataFrame(scaler.fit_transform(c0_for_lm), columns=c0_for_lm.columns).reset_index(drop=True, inplace=False)
    # label設定
    c0_for_lm_y = cluster_data.apply(lambda row: 1 if row['死亡'] != 0 else 2, axis=1)
        
    c0_for_lm_X = c0_for_lm_X[lst]
    
    return c0_for_lm_X, c0_for_lm_y


full_combine_X, full_combine_y = get_clusterN_logit(full_combine, lst_logit)
full_0_X, full_0_y = get_clusterN_logit(full_0, lst_logit)
full_1_X, full_1_y = get_clusterN_logit(full_1, lst_logit)
full_2_X, full_2_y = get_clusterN_logit(full_2, lst_logit)

full_out_X, full_out_y = get_clusterN_logit(full_out, lst_logit) # 新增

print(full_combine_y.value_counts())
print(full_0_y.value_counts())
print(full_1_y.value_counts())
print(full_2_y.value_counts())

2    214
1      6
dtype: int64
2    112041
1       441
dtype: int64
2    5665
1      73
dtype: int64
2    2394
1      65
dtype: int64


In [154]:
start_time = time.time()
# matrix_combine, score_combine, cm_combine = logistic_cm_gridsearch(full_combine_X,  full_combine_y)
matrix_0, score_0, cm_0 = logistic_cm_gridsearch(full_0_X, full_0_y)
matrix_1, score_1, cm_1 = logistic_cm_gridsearch(full_1_X, full_1_y)
matrix_2, score_2, cm_2 = logistic_cm_gridsearch(full_2_X, full_2_y)
# print(score_combine, score_0, score_1, score_2)
print(score_0, score_1, score_2)
end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

0.6911764705882353 0.66 0.65625
95.28781628608704


In [155]:
print(cm_0)
matrix_0

[[92 44]
 [40 96]]


Label  Precision    Recall  F1 Score
0  Class_0   0.696970  0.676471  0.686567
1  Class_1   0.685714  0.705882  0.695652

In [156]:
print(cm_1)
matrix_1

[[17  8]
 [ 9 16]]


Label  Precision  Recall  F1 Score
0  Class_0   0.653846    0.68  0.666667
1  Class_1   0.666667    0.64  0.653061

In [157]:
print(cm_2)
matrix_2

[[ 9  7]
 [ 4 12]]


Label  Precision  Recall  F1 Score
0  Class_0   0.692308  0.5625  0.620690
1  Class_1   0.631579  0.7500  0.685714

In [158]:
cm_0 + cm_1 + cm_2

array([[118,  59],
       [ 53, 124]], dtype=int64)

In [159]:
de = full_0_X.shape[0] + full_1_X.shape[0] + full_2_X.shape[0]
logit_avg_score = (full_0_X.shape[0]/de)*score_0 + (full_1_X.shape[0]/de)*score_1 + (full_2_X.shape[0]/de)*score_2
print(logit_avg_score)

0.6889824287134123


In [30]:
origin_X, origin_y = get_clusterN_logit(rbind_data, lst_logit)

start_time = time.time()

matrix_origin, score_origin, cm_origin = logistic_cm_gridsearch(origin_X, origin_y)
print(score_origin)

end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

0.6779661016949152
86.01647973060608
